### ISSUE TITLE
[Bug]: protected static ?int $passwordTimeout = 360;

### ISSUE THREAD

**Issue by arturodacostasoler** [juliomotol/filament-password-confirmation#3]
### What happened?

Hello.

-1/2.

¿Where should be placed the following code line for configuring the password confirmation timeout, and is this time in seconds or in other time measure?

protected static ?int $passwordTimeout = 360;

Important to change the "[README.md" file and provide precise instructions on where this code line should be placed for this functionality to work, and indicate the time measure (¿seconds, minutes, ...?).

I placed it on:

class AdminPanelProvider extends PanelProvider
{
    protected static ?int $passwordTimeout = 30;
...

and it doesn't work, it keeps allowing access after the first password confirmation.

-2/2.

Also, the password confirmation doesn't work for each independent Resource and after the first password confirmation in one of them I can access the other Resources where I've also specified the password confirmation to be used,

My Best Regards.

Cordially, with Respect and Appreciation.

Arturo Antonio DaCosta Soler
Engineer

### How to reproduce the bug

I placed it on:

class AdminPanelProvider extends PanelProvider
{
    protected static ?int $passwordTimeout = 30;
...

and it doesn't work, it keeps allowing access after the first password confirmation.

### Package Version

1.0.0

### PHP Version

8.3.6

### Laravel Version

11.5.0

### Which operating systems does with happen with?

Windows

**Comment by juliomotol** [comment]
I'm sorry for the confusion, the `$passwordTimout` is intended to be placed on the pages and resources that uses the `RequiresPasswordConfirmation` trait and is defined by the amount of seconds. 

I've made the necessary changes in the `README.md` for this. 

Also, I've made a new release where you can set the password timeout when registering the plugin

```php
RenewPasswordPlugin::make()
    ->passwordTimeout(10800) // Accepts int|null that represents the amount of seconds
```

Also, please see the note on the [Usage section](https://github.com/juliomotol/filament-password-confirmation/tree/v1.1.0?tab=readme-ov-file#usage) regarding the order of determining the password timeout.

>  the password confirmation doesn't work for each independent Resource and after the first password confirmation in one of them I can access the other Resources where I've also specified the password confirmation to be used

This is the intended behavior since this relies on [Laravel's Password Confirmation](https://laravel.com/docs/11.x/authentication#password-confirmation). In my personal opinion, its a better UX to just have the user confirm their password once as it can get pretty annoying when you always have to re-enter your password when you have to do something.

With that said, I would still be open to the idea if you ever consider opening a PR for it.
